name: rnaseq_discovery

channels:
  - bioconda
  - default
  - biocore
  - conda-forge
  - anaconda

dependencies:
  - star =2.7.1a
  - trinity =2.12.0
  - samtools =1.12
  - salmon =1.4.0
  - snakemake